main="./worker/index.js"
name = "dscvr-canvas"
compatibility_date = "2021-09-14"
compatibility_flags = [ "nodejs_compat_v2" ]
workers_dev = true
define = { __VUE_OPTIONS_API__ = "false", __VUE_PROD_DEVTOOLS__ = "false", __VUE_PROD_HYDRATION_MISMATCH_DETAILS__ = "false" }

[site]
bucket = "./dist/client"

[dev]
port = 3000

[[kv_namespaces]]
binding = "DB"
id = "60717b84316d4b8ea29cc43f956b7a3d"

[ai]
binding = "AI"

[vars]
IMGBB_API_KEY = ""
MINTER_SERVICE_HOST = ""
MINTER_INTERACTION_KEY = ""
